version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-hook-form
    versions:
    - 6.14.2
    - 6.15.1
    - 6.15.3
    - 6.15.4
    - 6.15.5
    - 7.0.0
    - 7.0.2
    - 7.0.4
    - 7.0.5
    - 7.0.7
    - 7.1.0
  - dependency-name: sass-loader
    versions:
    - 10.1.1
    - 11.0.0
